### ISSUE TITLE
Fix Pubmed data issues: author affiliations

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/litcovid#14]
Probably not worth it to actually fix this, but noting a couple instances where Pubmed doesn't correctly parse author affiliations:

https://pubmed.ncbi.nlm.nih.gov/31995857/#affiliation-1
https://pubmed.ncbi.nlm.nih.gov/32445440/#affiliation-1

Hopefully the Pubmed team will fix this on their own?  Not sure it's worth us building in the behavior to fix this...

**Comment by gtsueng** [comment]
Pubmed folks will fix errors in pubmed, but they need to be notified of them.  M2C volunteers caught duplicate entries in Pubmed (same abstract, 2 different IDs).  You just need to reach out to Pubmed to let them know and they will fix. Submit tickets about pubmed issues here: https://support.nlm.nih.gov/support/create-case/

Note, it may take a few days for them to fix an issue.

**Comment by flaneuse** [comment]
Thanks @gtsueng. Looking at this more, it looks like a NEJM problem, and [Pubmed is unlikely to fix it](https://support.nlm.nih.gov/knowledgebase/article/KA-04515/en-us?caseTitle=Fix%20author%20parsing%20on%20Pubmed%20records).  Submitted a request anyway (case CAS-547911-K8H5L6)
